name: sulaman_s_application007
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  dotted_border: ^2.1.0
  intl: ^0.18.0
  page_transition: ^2.1.0
  google_fonts: ^6.2.1
  flutter_sizer: ^1.0.5
  rounded_loading_button_plus: ^3.0.1
  circular_profile_avatar: ^2.0.5
  font_awesome_flutter: ^10.7.0
  getwidget: ^4.0.0
  animated_bottom_navigation_bar: ^1.3.3
  flutter_chat_ui: ^1.6.12
  http: ^1.2.1
  provider: ^6.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/logo.png
    - assets/images/1.jpg
    - assets/images/2.png
    - assets/images/fixer.jpg
    - assets/images/find.jpg
    - assets/images/edulogo.png
    - assets/dashboard/m.jpg
    - assets/dashboard/t.png
    - assets/dashboard/chat.png
    - assets/dashboard/message.png
    - assets/dashboard/chatting.png
    - assets/dashboard/blackgallery.png
    - assets/dashboard/coloredgallery.png
    - assets/dashboard/blacksmile.png
    - assets/dashboard/coloredsmile.png
    - assets/dashboard/phone (1).png
    - assets/dashboard/phone.png
    - assets/dashboard/smartphone.png
    - assets/dashboard/mobile.png
    - assets/dashboard/placeholder.png
    - assets/dashboard/location.png
    - assets/dashboard/fast-forward.png
    - assets/dashboard/foward.png
    - assets/dashboard/horoscope.png
    - assets/dashboard/todolist.png
    - assets/dashboard/notes.png
    - assets/dashboard/diary.png
    - assets/dashboard/sos.png
    - assets/dashboard/activity.png
  